version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "announcements-updated"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m0c617njyuzw"
s3_prefix = "announcements-updated"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
